siteTitle = "Blog by Dauren Akilbekov"
siteDescr = "Frontend and a little backend developer from Almaty, Kazakhstan."
siteAuthor = "Dauren Akilbekov"
siteAuthorShort = "Dauren"

siteTwitterUrl = "#"
siteGithubUrl = "https://github.com/akilbekov"
siteEmailUrl = "akilbekov@gmail.com"
siteStackoverflowUrl = "http://stackoverflow.com/users/4205611/dauren-akilbekov"
siteRssUrl = "#"

googleAnalyticsId = ""
